import dash
import dash_bootstrap_components as dbc
from dash import dcc, html, callback
from dash.dependencies import Input, Output
import pandas as pd

from app.data_utils import get_listings_data

# Initialize the Dash app
# Suppress callback exceptions because some components are generated by other callbacks
# (i.e., they exist in page layouts and not in the initial app.layout)
app = dash.Dash(__name__, use_pages=True, pages_folder='pages', external_stylesheets=[dbc.themes.BOOTSTRAP], suppress_callback_exceptions=True)
server = app.server

# Define the sidebar layout
sidebar = dbc.Nav(
    [
        dbc.NavLink("Choropleth", href="/", active="exact"),
        dbc.NavLink("Treemap", href="/treemap", active="exact"),
    ],
    vertical=True,
    pills=True,
    className="bg-light",
)

# Define the main app layout
app.layout = dbc.Container(
    [
        # Hidden store for raw data accessible across all pages
        dcc.Store(id='listings-data-store'),
        
        dcc.Location(id='url', refresh=False), # Add dcc.Location

        dbc.Row(
            [
                dbc.Col(html.H2("NYC Apartment Analytics", className="text-center"), width=12)
            ]
        ),
        html.Hr(),
        dbc.Row(
            [
                dbc.Col(sidebar, width=2, className=""),
                dbc.Col(dash.page_container, width=10),
            ]
        ),
    ],
    fluid=True,
)

# Global callback to load data into the store on any page load
@callback(
    Output('listings-data-store', 'data'),
    Input('url', 'pathname') # Triggered when the URL changes (i.e., page loads)
)
def load_initial_data(pathname):
    # This will load the data whenever a new page is loaded.
    df = get_listings_data()
    return df.to_json(date_format='iso', orient='split')

if __name__ == '__main__':
    app.run_server(debug=True)
