import dash
import dash_bootstrap_components as dbc
from dash import dcc, html, callback
from dash.dependencies import Input, Output
import pandas as pd
from datetime import date
from io import StringIO

from app.data_utils import get_listings_data

# Initialize the Dash app
# Suppress callback exceptions because some components are generated by other callbacks
# (i.e., they exist in page layouts and not in the initial app.layout)
dbc_css = "https://cdn.jsdelivr.net/gh/AnnMarieW/dash-bootstrap-templates/dbc.min.css"

app = dash.Dash(__name__, 
                use_pages=True, 
                pages_folder='pages', 
                # external_stylesheets=[dbc.themes.BOOTSTRAP], 
                # external_stylesheets=[dbc.themes.FLATLY],
                external_stylesheets=[dbc.themes.CYBORG, dbc_css],
                suppress_callback_exceptions=True)
server = app.server

# Define the sidebar layout
sidebar = dbc.Nav(
    [
        dbc.NavLink("Choropleth", href="/", active="exact"),
        dbc.NavLink("Treemap", href="/treemap", active="exact"),
        dbc.NavLink("Table View", href="/table", active="exact"),
    ],
    vertical=True,
    pills=True,
    className="bg-light",
)

# Define the main app layout
app.layout = dbc.Container(
    [
        # Hidden store for raw data accessible across all pages
        dcc.Store(id='raw-listings-store'),
        # Hidden store for filtered data accessible across all pages
        dcc.Store(id='filtered-listings-store'),
        
        dcc.Location(id='url', refresh=False), # Add dcc.Location

        dbc.Row(
            [
                dbc.Col(html.H2("NYC Apartment Analytics", className="my-2"), width=6),
                dbc.Col([
                    dbc.Label("Filter by Available Date:"),
                    dcc.DatePickerRange(
                        id='date-picker-range',
                        min_date_allowed=date(2025, 5, 1),
                        max_date_allowed=date(2026, 12, 31),
                        start_date=date(2025, 5, 1),
                        end_date=date(2026, 12, 31),
                        className="w-100"
                    ),
                ], width=6, className="my-2"),
            ],
        ),
        html.Hr(),
        dbc.Row(
            [
                dbc.Col(sidebar, width=2, className=""),
                dbc.Col(dash.page_container, width=10),
            ]
        ),
    ],
    fluid=True,
)

# Global callback to load data into the store on any page load
@callback(
    Output('raw-listings-store', 'data'),
    Input('url', 'pathname') # Triggered when the URL changes (i.e., page loads)
)
def load_initial_data(pathname):
    # This will load the data whenever a new page is loaded.
    df = get_listings_data()
    # Ensure 'available_date' is a datetime object for filtering
    df['available_date'] = pd.to_datetime(df['available_at'])
    return df.to_json(date_format='iso', orient='split')

# Global callback to filter data based on the date picker
@callback(
    Output('filtered-listings-store', 'data'),
    Input('raw-listings-store', 'data'),
    Input('date-picker-range', 'start_date'),
    Input('date-picker-range', 'end_date')
)
def filter_data_by_date(raw_data_json, start_date, end_date):
    if not raw_data_json:
        return None
    df = pd.read_json(StringIO(raw_data_json), orient='split')
    filtered_df = df[(df['available_date'] >= start_date) & (df['available_date'] <= end_date)]
    return filtered_df.to_json(date_format='iso', orient='split')

if __name__ == '__main__':
    app.run_server(debug=True)
